---
component:
  type: asphalt_sanic_demo.app:ApplicationComponent
  components:
    redis:
    server:
      host: 0.0.0.0
      port: 9000
    templating:
      backend: jinja2
      package_name: asphalt_sanic_demo
      package_path: server/templates

logging:
  version: 1
  disable_existing_loggers: false
  formatters:
    color:
      class: colorlog.ColoredFormatter
      format: '%(log_color)s%(levelname)-5.5s %(asctime)s%(reset)s %(blue)s[%(name)s:%(lineno)s][%(threadName)s]%(reset)s %(message)s'
    generic:
      format: '[%(asctime)s %(levelname)s] %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      formatter: color
  loggers:
    asphalt:
      level: INFO
    asphalt_sanic_demo:
      level: INFO
  root:
    handlers: [console]
    level: INFO
