---
component:
  type: asphalt_sanic_demo.app:ApplicationComponent
  components:
    redis:
    server:
      port: 9000
    templating:
      backend: jinja2
      package_name: asphalt_sanic_demo
      package_path: templates

logging:
  version: 1
  disable_existing_loggers: false
  formatters:
    default:
      format: '[%(asctime)s %(levelname)s] %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      formatter: default
  loggers:
    root:
      handlers: [console]
      level: DEBUG
    asphalt_sanic_demo:
      handlers: [console]
      level: DEBUG
      propagate: false
